mybatis:
  readonly-mapper-locations:
      - classpath*:/mapper/*.xml # 数组，用 -  接收
      - classpath*:/mapper/readonlyMapper/*.xml # 数组，用 -  接收
  mapper-locations:
      - classpath*:/mapper/*.xml
      - classpath*:/mapper/mapper/*.xml # 数组，用 -  接收
  type-aliases-package: com.cn.xt.mp.mpModel
  config-location: classpath:mybatis-config.xml

      #    order: 1

#邮件
#  mail:
#    host: smtp.exmail.qq.com
#    username: momosv@momosv.cn
#    password: k8f4yavHZ4jQgUnx
#    properties:
#      mail:
#        self:
#          username: momo
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#            port: 465
#          auth: true
#          starttls:
#            enable: true
#            required: true

