server:
  port: 80
  servlet:
    session:
      timeout: 60m
spring:
  profiles:
    active: base,freemark,mybatis
#  session:
#      store-type: none


     # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB


logging:
  config: classpath:logback.xml
  path: logs
  level:
    org:
      springframework:
         security: INFO

      #    order: 1

#邮件
#  mail:
#    host: smtp.exmail.qq.com
#    username: momosv@momosv.cn
#    password: k8f4yavHZ4jQgUnx
#    properties:
#      mail:
#        self:
#          username: momo
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#            port: 465
#          auth: true
#          starttls:
#            enable: true
#            required: true



#security:
#  user:
#    name: momo
#    password: 123
#  basic:
#    enabled: false
