server:
  port: 80
spring:
  freemarker:
    request-context-attribute: req
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/static/
    charset: UTF-8
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    settings:
      number_format: '0.##'
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
